#!/bin/sh

#SBATCH --job-name=ds001338-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001338-fmriprep/.reproman/jobs/local/20221114-172529-7954/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001338-fmriprep/.reproman/jobs/local/20221114-172529-7954/stderr

#SBATCH --nodes=6
#SBATCH --ntasks=22
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001338-fmriprep/.reproman/jobs/local/20221114-172529-7954

module load launcher
module load remora
module load ooops
set_io_param_batch $SLURM_JOBID 0 low
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 21); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun